#ifndef ARM64_EXECUTOR_TEMPLATES_H
#define ARM64_EXECUTOR_TEMPLATES_H

#define TEMPLATE_ENTER          0x00001111
#define TEMPLATE_INSERT_TC      0x00002222
#define TEMPLATE_RETURN         0x00003333

enum Templates {
	UNSET_TEMPLATE,
	PRIME_AND_PROBE_TEMPLATE,
	FLUSH_AND_RELOAD_TEMPLATE,
};

int load_template(size_t tc_size);

#endif // ARM64_EXECUTOR_TEMPLATES_H
